### PR TITLE
Fix #670 - Package release string for EL platform

### LINKED ISSUE #670: Fix package suffix spec test
This is related to PR #615 

```
Failures:

  1) sensu package setting version with redhat platform version suffix should contain Package[sensu] with ensure => "0.29.0-1.el7"
     Failure/Error:
       it { should contain_package('sensu').with(
         :ensure => '0.29.0-1.el7'
       ) }

       expected that the catalogue would contain Package[sensu] with ensure set to "0.29.0-1.el7" but it is set to "0.29.0-1.el7.el7"
     # ./spec/classes/sensu_package_spec.rb:53:in `block (5 levels) in <top (required)>'

Finished in 30.9 seconds (files took 1.44 seconds to load)
369 examples, 1 failure
```

### PR DESCRIPTION
**Pull request by ghoneycutt**
https://github.com/sensu/sensu-puppet/issues/670

### CODE REVIEW

File: spec/classes/sensu_package_spec.rb [hunk 1]
```diff
@@ -30,12 +30,12 @@
     context 'setting version' do
       context 'without platform version suffix' do
         let(:params) { {
-          :version              => '0.9.10',
+          :version              => '0.29.0',
           :sensu_plugin_version => 'installed',
         } }
 
         it { should contain_package('sensu').with(
-          :ensure => '0.9.10.el7'
```
Comment (ghoneycutt) [inline spec/classes/sensu_package_spec.rb]: This expected behavior is what was causing the issue. The actual expected behavior is if you don't specify el# then you don't use it. This may have been useful many releases ago when naming was different, though all releases now use the correct naming.

http://repositories.sensuapp.org/yum/7/x86_64/

**Comment by ghoneycutt** [comment]
Solves #670
