### PR TITLE
Fix for when version query returns malformed version

### LINKED ISSUE #1278: [bug] Agent fails to set subscriptions, when using a custom built backend
## Description of problem
Using a custom build of the sensu-go-backend, yields the following error on both Linux (Ubuntu) and Windows (I'm setting a subscription with the name `debug`):
```
Error: Could not set 'present' on ensure: Malformed version number string (devel) (file: /etc/puppetlabs/code/environments/bugreporting/modules/sensu/manifests/agent/subscription.pp, line: 41)
Error: Could not set 'present' on ensure: Malformed version number string (devel) (file: /etc/puppetlabs/code/environments/bugreporting/modules/sensu/manifests/agent/subscription.pp, line: 41)
Wrapped exception:
Malformed version number string (devel)
Error: /Stage[main]/Sensu::Agent/Sensu::Agent::Subscription[debug]/Sensu_agent_entity_config[sensu::agent::subscription debug]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: Malformed version number string (devel) (file: /etc/puppetlabs/code/environments/bugreporting/modules/sensu/manifests/agent/subscription.pp, line: 41)
```

Replacing the backend file with .deb packges, makes it work. (`apt install --reinstall sensu-go-backend`)

## Command used and debugging output

- What does your puppet config look like (including any hiera config): very simple:
```
# Hiera
sensu::agent::subscriptions:
  - debug

# base.pp
include sensu
class { 'sensu::agent':
  entity_name   => $facts['networking']['fqdn'],
  backends      => ['sensu.domain.com:8081'],
  subscriptions => lookup('sensu::agent::subscriptions', Array, 'unique').downcase().sort(),
  labels        => lookup('sensu::agent::labels', Hash, 'hash'),
  annotations   => lookup('sensu::agent::annotations', Hash, 'hash'),
}
```
- Is this a masterless or master based puppet setup?: Master based.

## Platform and version information

- Your OS: Servers: Ubuntu 18.04 and 20.04, Windows 2012 R2, 2016, 2019; the backend runs on Ubuntu 18.04
- Your Ruby version: `ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]`
- Your version of Puppet: Puppet v6.18.0 (Open Source)
- Your version of Sensu: `sensu-backend version 6.1.0+ee, enterprise edition, build be1e65933de5be15a65066227f007ae369af1449, built 2020-10-02T01:15:38Z, built with go1.13.15` (custom built - see below)
- Your version of this module: 5.2.0 (:latest)

## Anything else to add that you think will be helpful?
I've built the backend like so:
1. Cloned the sensu-go repository
2. checked out `origin/release/6.1`
3. Built it: `go build -o bin/sensu-backend-custom ./cmd/sensu-backend`
4. Updated the Sensu-backend service, to use the `sensu-backend-custom`

`sensu-backend version` returns the same version string for my custom built version, and the prepacked one. Am i missing a setting?

Also, when running with debug, the following shows up, before the error:
```
Debug: method=get url=https://sensu.domain.com:8080/version path=/version
Debug: Sensu API: Using token $token
Debug: RESPONSE: 200                              
{"etcd":{"etcdserver":"3.3.22","etcdcluster":"3.3.0"},"sensu_backend":"(devel)"}
```

### PR DESCRIPTION
**Pull request by treydock**
# Pull Request Checklist

## Description

Fix version comparison logic to be a bit more resilient so that if the version returned is not expected the code does not raise exceptions.

Some of the unit test changes were to address the unit tests essentially testing nothing and not being really valid tests.

## Related Issue

Fixes #1278

### CODE REVIEW

File: lib/puppet/provider/sensu_api.rb [hunk 1]
```diff
@@ -260,7 +259,10 @@ def self.version_cmp(v)
       @current_version = version
     end
     return true if @current_version.nil?
-    return Gem::Version.new(@current_version) >= Gem::Version.new(v)
+    Gem::Version.new(@current_version) >= Gem::Version.new(v)
+  rescue ArgumentError => e
+    Puppet.debug "Unable to compare version #{@current_version} with needed version #{v}: #{e}"
```
Comment (ghoneycutt) [inline lib/puppet/provider/sensu_api.rb:264]: Document this behavior along with an explanation and link to the issue

Comment (treydock) [reply lib/puppet/provider/sensu_api.rb:266]: Comments added.

**Review by ghoneycutt — APPROVED** [review]

**Comment by ghoneycutt** [comment]
Released in v5.2.1
