### PR TITLE
(#495) Notify Service[sensu-enterprise] from Sensu::Check resources

### LINKED ISSUE #495: $check_notify does not load sensu::enterprise::service
When you set `sensu::check`, this module does not notify `Service["sensu-enterprise"]`.

I've look at [code](https://github.com/sensu/sensu-puppet/blob/master/manifests/init.pp#L442), there is "ugly hack" but that hack does not work with sensu-enterprise. 
If needed, I can make PR for this but just tell me if I'm on right direction. 
How `Service["sensu-enterprise"]` should get notified when check is added?

EDIT: 
Maybe I should be more descriptive, so if you have understand what is the problem, you might stop reading after this point. 

When I add new check ex:

``` puppet
sensu::check { 'check_cpu':
    command     => 'check-cpu.rb -w 85 -c 95',
  }
```

and run `puppet apply` returns this 

``` log
Notice: /Stage[main]/Fb_sensu::Checks::System/Sensu::Check[check_cpu]/Sensu_check[check_cpu]/ensure: created
Notice: /Stage[main]/Sensu::Client::Service/Service[sensu-server]: Triggered 'refresh' from 2 events
```

The problem here is that `sensu-server` is being refreshed and not `sensu-enterprise` 

EDIT: relevant PR #388

### PR DESCRIPTION
**Pull request by jeffmccune**
Without this patch The sensu-enterprise service is not notified
automatically when `sensu::check` resources are declared.  This patch
addresses the problem by checking the catalog for the service and
automatically adding the notify relationship.

resolves #502 
resolves #495
closes #653

### CODE REVIEW

File: lib/puppet/type/sensu_check.rb [hunk 1]
```diff
@@ -21,10 +21,13 @@ def should
...
 
-    self[:notify] = [
-      "Service[sensu-client]",
-      "Service[sensu-server]",
-    ].select { |ref| catalog.resource(ref) }
+    if c = catalog
+      self[:notify] = [
+        "Service[sensu-client]",
+        "Service[sensu-server]",
+        "Service[sensu-enterprise]",
```
Comment (ghoneycutt) [inline lib/puppet/type/sensu_check.rb]: if Service[sensu-enterprise] is not in the catalog, because we aren't using enterprise, does this cause a problem?

Comment (jeffmccune) [inline lib/puppet/type/sensu_check.rb]: I expect no problem because`Array#select` filter out the resource ref when absent from the catalog.

Comment (ghoneycutt) [inline lib/puppet/type/sensu_check.rb]: Have you verified with `vagrant up` ?

Comment (jeffmccune) [inline lib/puppet/type/sensu_check.rb]: No, will do so now.

Comment (jeffmccune) [inline lib/puppet/type/sensu_check.rb]: @ghoneycutt I modified the provisioning manifest for `sensu-server-enterprise` to manage Service[sensu-enterprise] instead of Service[sensu-server].  Take a look at this change in 1d694e4, I assumed `tests/sensu-server-enterprise.pp` is intended to setup sensu-enterprise.

With `vagrant up sensu-server`, the notification doesn't cause a problem as we expect.  With `vagrant up sensu-server-enterprise`, the notification does properly notify `Service[sensu-enterprise]' when a managed `sensu::check` resource changes state.

**Comment by ghoneycutt** [comment]
@jeffmccune see PR #502 where they made similar changes, but to other files as well.

**Comment by jeffmccune** [comment]
@ghoneycutt Got it, I'll update this PR to add the notify to all of the files referenced in #502

**Comment by jeffmccune** [comment]
@ghoneycutt Notifications and spec coverage added to all types listed in #502  This is ready for another review.

File: tests/sensu-server-enterprise.pp [hunk 2]
```diff
@@ -9,18 +9,19 @@
...
     install_repo              => true,
-    server                    => true,
+    enterprise                => true,
+    enterprise_user           => $facts['se_user'],
+    enterprise_pass           => $facts['se_pass'],
     manage_services           => true,
     manage_user               => true,
     rabbitmq_password         => 'correct-horse-battery-staple',
     rabbitmq_vhost            => '/sensu',
-    api                       => true,
```
Comment (ghoneycutt) [inline tests/sensu-server-enterprise.pp]: Why was the API portion removed?

**Comment by jeffmccune** [comment]
The api portion was removed because the API is mutually exclusive with setting sensu::enterprise => true.  See init.pp L573:

```puppet
  if ( $enterprise and $api ) or ( $enterprise and $server ) {
    fail('Sensu Enterprise: sensu-enterprise replaces sensu-server and sensu-api')
  }
```

**Comment by ghoneycutt** [comment]
Released in v2.19.1
